refactor(scripts): update shebang lines to use env and fix indentation
- Change shebang from #!/bin/bash to #!/usr/bin/env bash in multiple scripts
- Change shebang from #!/bin/dash to #!/usr/bin/env dash in multiple scripts
- Change shebang from #!/bin/zsh to #!/usr/bin/env zsh in fzf-man and select-manpath
- Fix indentation in compare-folders script options parsing

diff --git a/.local/scripts/compare-folders b/.local/scripts/compare-folders
--- a/.local/scripts/compare-folders
+++ b/.local/scripts/compare-folders
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # Compare folders using diff command.
 
 if [ $# -lt 2 ]; then
@@ -22,21 +22,21 @@ COLOR_DIFF=false
 shift 2
 while getopts "f:wsuc" opt; do
   case $opt in
-    f) FILTER="$OPTARG" ;;
-    w) IGNORE_WHITESPACE=true ;;
-    s)
-      SHOW_DIFF=true
-      DIFF_FORMAT="-y"
-      ;;
-    u)
-      SHOW_DIFF=true
-      DIFF_FORMAT="-u"
-      ;;
-    c) COLOR_DIFF=true ;;
-    ?)
-      echo "Invalid option"
-      exit 1
-      ;;
+  f) FILTER="$OPTARG" ;;
+  w) IGNORE_WHITESPACE=true ;;
+  s)
+    SHOW_DIFF=true
+    DIFF_FORMAT="-y"
+    ;;
+  u)
+    SHOW_DIFF=true
+    DIFF_FORMAT="-u"
+    ;;
+  c) COLOR_DIFF=true ;;
+  ?)
+    echo "Invalid option"
+    exit 1
+    ;;
   esac
 done
 
